### ISSUE TITLE
"invalid token"

### ISSUE THREAD

**Issue by MrFums** [peakxl/twitch-drop-claimer#116]
Keep getting flagged for an invalid token - please can someone sanity check it for me or am I being stupid and grabbing it from the wrong location? 
![image](https://github.com/peakxl/twitch-drop-claimer/assets/57535680/e5130db5-418a-47d3-af28-fadd47087cee)

**Comment by QuentinJ54** [comment]
Good morning,
Use "editthiscookie" it's a browser extension. you will be able to find your cookie easily.

**Comment by MrFums** [comment]
Thank you !
